version: '3.8'

services:
  mysql-employee-service:
    image: mysql:8.0
    container_name: mysql_employee
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeeservice_db
    ports:
      - "3307:3306"
    networks:
      - springboot-microservices-network

  mysql-department-service:
    image: mysql:8.0
    container_name: mysql_department
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: departmentservice_db
    ports:
      - "3308:3306"
    networks:
      - springboot-microservices-network

  mysql-organization-service:
    image: mysql:8.0
    container_name: mysql_organization
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organizationservice_db
    ports:
      - "3309:3306"
    networks:
      - springboot-microservices-network

  mysql-notification-service:
    image: mysql:8.0
    container_name: mysql_notification
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notificationservice_db
    ports:
      - "3310:3306"
    networks:
      - springboot-microservices-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: mysql_employee,mysql_department,mysql_organization,mysql_notification  # Je kunt verbinden met andere databases via deze hostnames
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"
    networks:
      - springboot-microservices-network

networks:
  springboot-microservices-network:
    driver: bridge
